(defcaixa
  :name
  "lava-cloudflare"
  :kind
  :Biblioteca
  :ecosystem
  :rust-single-crate
  :package
  {:name "lava-cloudflare"
   :version "0.1.0"
   :description "Tatara-lisp typed surface for cloudflare resources. Auto-generated by lava-forge from the cloudflare TF provider schema. Pangea-cloudflare analog."
   :license "MIT"
   :repository "https://github.com/pleme-io/lava-cloudflare"}
  :ci-config
  {:bump {:default-type "patch"}
   :publish {:no-verify true}}
  :workflows
  [:auto-release :pre-merge-gate :security-gate])
