//! lava-cloudflare — autogenerated typed Cloudflare resource catalog.
//!
//! Mirrors pangea-cloudflare. Each typed shape lives under
//! `resources/cloudflare_*.tlisp`, generated via lava-forge from the
//! terraform-provider-cloudflare schema kept under `schema.json`.
//!
//! ## Regenerating
//!
//! ```bash
//! # Refresh schema.json by running against a live tofu workspace:
//! tofu providers schema -json > schema.json
//! # Re-emit the typed shapes:
//! lava-forge generate --schema schema.json --out resources
//! ```
//!
//! Consumers list the available resources via the `_index.tlisp`
//! aggregator under `resources/`, and load any one via `include_str!`
//! at compile time.

#![allow(clippy::module_name_repetitions)]

/// Path to the directory holding the autogenerated `.tlisp` resource
/// shapes, relative to `CARGO_MANIFEST_DIR`.
pub const RESOURCES_DIR: &str = "resources";

/// Catalog index of every typed Cloudflare resource shape this crate
/// ships. Mirrors the `_index.tlisp` aggregator on disk.
pub const RESOURCES: &[&str] = &[
    "cloudflare_zone",
    "cloudflare_dns_record",
    "cloudflare_r2_bucket",
    "cloudflare_r2_bucket_cors",
    "cloudflare_r2_custom_domain",
    "cloudflare_tunnel",
    "cloudflare_tunnel_config",
    "cloudflare_zone_settings_override",
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_registered_resource_has_a_tlisp_file() {
        let base = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join(RESOURCES_DIR);
        for name in RESOURCES {
            let p = base.join(format!("{name}.tlisp"));
            assert!(p.exists(), "missing typed shape on disk: {}", p.display());
        }
    }

    #[test]
    fn index_tlisp_exists_alongside_resources() {
        let base = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join(RESOURCES_DIR);
        assert!(base.join("_index.tlisp").exists(), "_index.tlisp not generated");
    }

    #[test]
    fn schema_json_is_present_for_regen() {
        let base = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
        assert!(base.join("schema.json").exists(), "schema.json not present");
    }
}
